-- LandsandHousing Property Concierge — seed
-- GENERATED by scripts/gen-seed.mjs from src/data/mockData.ts — do not hand-edit.
-- Regenerate with: node scripts/gen-seed.mjs
--
-- Upserts by natural key, so re-running refreshes catalogue copy without ever
-- touching lh_lead / lh_conversation / lh_booking rows.
--
-- 6 properties, 14 knowledge documents.

INSERT INTO lh_property (
  id, title, property_type, purpose, location, zone, price_raw, currency,
  price_label, beds, baths, size_sqm, plot_sqm, title_document, description,
  highlights, features, image_url, status, editorial_highlight, is_illustrative
) VALUES
(
  'prop-1', 'The Aka Horizon Commercial Centre', 'Commercial', 'Sale', 'Aka Road Commercial Corridor, Uyo', 'Commercial Corridors',
  420000000, 'NGN', '₦420,000,000',
  NULL, NULL, 1450, 2200,
  '1,450 sqm built area', 'A striking contemporary commercial property situated directly on the high-traffic Aka Road corridor. Engineered for corporate headquarters, financial institutions, or multi-tenant retail and executive suites with dedicated parking and generator substations.', '["Direct arterial road frontage with 45m span","Certificate of Occupancy (C of O) in place","Integrated heavy-duty power infrastructure & borehole","3-level open-plan floorplates ready for custom fit-out"]'::jsonb, '{"galleryImages":["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1600&auto=format&fit=crop","https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1400&auto=format&fit=crop"],"featured":true,"location":"Aka Road Commercial Corridor, Uyo","typeLabel":"Commercial","purposeLabel":"Sale"}'::jsonb,
  'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1600&auto=format&fit=crop', 'exclusive_advisory',
  true, true
),
(
  'prop-2', 'The Haven Contemporary Villa', 'Residential', 'Sale', 'Shelter Afrique Estate, Uyo', 'Shelter Afrique',
  185000000, 'NGN', '₦185,000,000',
  5, 6, 620, 950,
  '620 sqm built', 'An architectural residence designed with double-height ceiling voids, floor-to-ceiling glass fenestration, private swimming pool, and tropical perimeter greenery in Uyo’s premier gated residential enclave.', '["Private security perimeter and automated access","Fully fitted minimalist chef kitchen & wet pantry","Private swimming pool and poolside pavilion","Registered Governor’s Consent on survey"]'::jsonb, '{"galleryImages":["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1400&auto=format&fit=crop"],"featured":true,"location":"Shelter Afrique Estate, Uyo","typeLabel":"Residential","purposeLabel":"Sale"}'::jsonb,
  'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1400&auto=format&fit=crop', 'available',
  false, true
),
(
  'prop-3', 'Ewet Executive Residence & Terrace', 'Residential', 'Sale', 'Ewet Housing Estate, Uyo', 'Ewet Housing Estate',
  145000000, 'NGN', '₦145,000,000',
  4, 5, 480, 750,
  '480 sqm built', 'A serene detached family residence celebrating clean lines, warm timber accents, and shaded outdoor terraces situated within the tree-lined avenues of Ewet Housing Estate.', '["Established high-security neighborhood with paved drainage","Independent 2-room staff quarters (BQ)","Solar hybrid backup system pre-wired","Pristine land title documents"]'::jsonb, '{"galleryImages":["https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=1400&auto=format&fit=crop"],"featured":true,"location":"Ewet Housing Estate, Uyo","typeLabel":"Residential","purposeLabel":"Sale"}'::jsonb,
  'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1400&auto=format&fit=crop', 'available',
  false, true
),
(
  'prop-4', 'Osongama Prime Development Parcel', 'Land', 'Invest', 'Osongama Estate Extension, Uyo', 'Osongama Estate',
  48000000, 'NGN', '₦48,000,000',
  NULL, NULL, NULL, 1800,
  NULL, 'A completely dry, level corner parcel perfectly positioned for private residential development or luxury semi-detached townhouse development in the fast-appreciating Osongama corridor.', '["Clean registered survey and registered deed","Direct access to tarred access link road","Fast capital appreciation trajectory","Immediate construction readiness"]'::jsonb, '{"galleryImages":["https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1400&auto=format&fit=crop","https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?q=80&w=1400&auto=format&fit=crop"],"featured":false,"location":"Osongama Estate Extension, Uyo","typeLabel":"Land","purposeLabel":"Invest"}'::jsonb,
  'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1400&auto=format&fit=crop', 'available',
  false, true
),
(
  'prop-5', 'Abak Road Mixed-Use Commercial Plaza', 'Commercial', 'Rent', 'Abak Road Commercial Hub, Uyo', 'Commercial Corridors',
  12000000, 'NGN', '₦12,000,000 / year',
  NULL, NULL, 450, NULL,
  '450 sqm floorplate', 'High-visibility ground and first floor commercial retail / banking hall space offering prime vehicular visibility, modern curtain walling, and reliable utility backup.', '["Central location along major civic artery","Adequate customer surface parking","Professional facility management services included","High foot and transit traffic"]'::jsonb, '{"galleryImages":["https://images.unsplash.com/photo-1577495508048-b635879837f1?q=80&w=1400&auto=format&fit=crop"],"featured":false,"location":"Abak Road Commercial Hub, Uyo","typeLabel":"Commercial","purposeLabel":"Rent"}'::jsonb,
  'https://images.unsplash.com/photo-1577495508048-b635879837f1?q=80&w=1400&auto=format&fit=crop', 'available',
  false, true
),
(
  'prop-6', 'City Centre Corporate Office Suites', 'Commercial', 'Sale', 'Wellington Bassey Way / City Centre, Uyo', 'Uyo City Centre',
  290000000, 'NGN', '₦290,000,000',
  NULL, NULL, 980, 1200,
  '980 sqm gross area', 'Premium administrative and professional consulting building in the heart of Uyo’s civic and banking district. Ideal for legal practices, engineering firms, or corporate regional headquarters.', '["Walking distance to government secretariats and major banks","Dedicated transformer and dual backup generators","Secured perimeter with electronic boom barriers","High rental yield potential for institutional investors"]'::jsonb, '{"galleryImages":["https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=1400&auto=format&fit=crop"],"featured":false,"location":"Wellington Bassey Way / City Centre, Uyo","typeLabel":"Commercial","purposeLabel":"Sale"}'::jsonb,
  'https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=1400&auto=format&fit=crop', 'available',
  false, true
)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  property_type = EXCLUDED.property_type,
  purpose = EXCLUDED.purpose,
  location = EXCLUDED.location,
  zone = EXCLUDED.zone,
  price_raw = EXCLUDED.price_raw,
  currency = EXCLUDED.currency,
  price_label = EXCLUDED.price_label,
  beds = EXCLUDED.beds,
  baths = EXCLUDED.baths,
  size_sqm = EXCLUDED.size_sqm,
  plot_sqm = EXCLUDED.plot_sqm,
  title_document = EXCLUDED.title_document,
  description = EXCLUDED.description,
  highlights = EXCLUDED.highlights,
  features = EXCLUDED.features,
  image_url = EXCLUDED.image_url,
  status = EXCLUDED.status,
  editorial_highlight = EXCLUDED.editorial_highlight,
  is_illustrative = EXCLUDED.is_illustrative,
  updated_at = now();

INSERT INTO lh_knowledge (slug, category, title, content, meta) VALUES
(
  'business-profile', 'business', 'LandsandHousing — company profile and contact details', 'LandsandHousing is a Commercial Real Estate Agency & Property Advisory based at 181 Aka Rd, Uyo 520001, Akwa Ibom, Nigeria. Phone: 0805 632 1856. WhatsApp: +2348056321856. Rating: 4.9 / 5 from 19 Google reviews. Operating hours: Open 24 hours. A client review reads: "Splendid and professional services, thank you & keep setting the pace."', '{"phone":"+2348056321856","whatsapp":"2348056321856"}'::jsonb
),
(
  'location-loc-1', 'location', 'Ewet Housing Estate — Refined Living & Diplomatic Enclaves', 'Ewet Housing Estate: Refined Living & Diplomatic Enclaves. Uyo’s classic prestigious residential quarter, celebrated for tranquil tree-shaded avenues, high security, and stately detached residences. Curated Residential listings in this area. Character: Prestigious Residential.', '{"propertyCount":"Curated Residential","character":"Prestigious Residential"}'::jsonb
),
(
  'location-loc-2', 'location', 'Shelter Afrique — Modern Architectural Estates', 'Shelter Afrique: Modern Architectural Estates. An elite gated community featuring contemporary architectural homes, private security perimeters, and spacious luxury living standards. Executive Residences listings in this area. Character: Luxury Gated Community.', '{"propertyCount":"Executive Residences","character":"Luxury Gated Community"}'::jsonb
),
(
  'location-loc-3', 'location', 'Osongama Estate — Contemporary Family & Investment Enclave', 'Osongama Estate: Contemporary Family & Investment Enclave. A thriving residential and expansion district characterized by high capital appreciation and modern private townhouses. Emerging & Developed listings in this area. Character: High-Growth Enclave.', '{"propertyCount":"Emerging & Developed","character":"High-Growth Enclave"}'::jsonb
),
(
  'location-loc-4', 'location', 'Aka & Abak Commercial Corridors — Arterial Commercial Vitality', 'Aka & Abak Commercial Corridors: Arterial Commercial Vitality. Strategic high-traffic corridors providing premium commercial frontage for corporate headquarters, retail plazas, and medical centers. Commercial & Retail listings in this area. Character: Prime Commercial.', '{"propertyCount":"Commercial & Retail","character":"Prime Commercial"}'::jsonb
),
(
  'location-loc-5', 'location', 'Uyo City Centre — Civic Core & Administrative Hub', 'Uyo City Centre: Civic Core & Administrative Hub. The historic and financial heartbeat of Akwa Ibom State, where corporate banking offices and administrative buildings converge. Office & Civic listings in this area. Character: Central Business District.', '{"propertyCount":"Office & Civic","character":"Central Business District"}'::jsonb
),
(
  'location-loc-6', 'location', 'Strategic Investment Areas — Expansion Corridors & Land Banks', 'Strategic Investment Areas: Expansion Corridors & Land Banks. Selected growth axes around Ring Road corridors with strong infrastructural momentum for strategic land banking. Land & Investment listings in this area. Character: Growth Corridors.', '{"propertyCount":"Land & Investment","character":"Growth Corridors"}'::jsonb
),
(
  'service-service-sales', 'service', 'Property Sales — Acquisition & Divestment with Rigorous Due Diligence', 'Property Sales (Acquisition & Divestment with Rigorous Due Diligence): Identify the right opportunity, assess the property, and move forward with confidence. We advise buyers and investors through comprehensive title verification, negotiation, and formal transaction execution. Key deliverables: Title and survey document verification across Akwa Ibom State ministries; Transparent negotiation on commercial and high-value residential assets; Confidential representation for private buyers, diasporic investors, and corporate entities.', '{"tag":"Advisory & Transaction"}'::jsonb
),
(
  'service-service-costing', 'service', 'Property Costing — Accurate Valuation & Financial Feasibility', 'Property Costing (Accurate Valuation & Financial Feasibility): Understand the value of a property before making a major financial decision. We provide transparent, evidence-grounded property costing for land, commercial builds, and residential structures. Key deliverables: Comparative market valuation grounded in verifiable Uyo transactional data; Development cost estimation and material benchmarking for developers; Rental yield analysis and long-term asset performance forecasting.', '{"tag":"Valuation & Analysis"}'::jsonb
),
(
  'service-service-management', 'service', 'Property Management — Asset Protection & Ongoing Operational Performance', 'Property Management (Asset Protection & Ongoing Operational Performance): Keep properties performing, protected, and professionally managed. We relieve property owners of operational burdens while ensuring high tenant quality and timely revenue collection. Key deliverables: Rigorous tenant vetting, onboarding, and structured lease administration; Proactive preventative maintenance and facility upkeep coordination; Detailed financial reporting and prompt rental disbursement to owners.', '{"tag":"Asset Management"}'::jsonb
),
(
  'service-service-training', 'service', 'Training of Marketers — Professional Development for Real Estate Marketers', 'Training of Marketers (Professional Development for Real Estate Marketers): Practical real estate training for marketers building stronger property businesses. Equipping industry practitioners with essential legal basics, digital client advisory standards, and ethical negotiation skills. Key deliverables: Foundational property law and documentation comprehension in Nigeria; Client relationship advisory and consultative sales methodologies; Ethical representation and market research analytical tools.', '{"tag":"Industry Training"}'::jsonb
),
(
  'insight-insight-1', 'insight', 'Navigating Title Verification and Land Due Diligence in Akwa Ibom (Buying)', 'Navigating Title Verification and Land Due Diligence in Akwa Ibom — A structured breakdown of essential documentation—from Registered Surveys to Governor’s Consent—ensuring buyers protect capital when acquiring land in Uyo. Acquiring real estate in Uyo requires a systematic approach to documentation verification before any commitment of capital occurs. 1. Cadastral Survey Verification: Always cross-reference the survey plan coordinates with the Akwa Ibom State Ministry of Lands and Water Resources to confirm zoning boundaries and road setbacks. 2. Title Classification: Distinguish clearly between Village Allocation, Deed of Conveyance, and statutory Certificate of Occupancy (C of O) or Governor’s Consent. 3. Encumbrance Checks: Investigate whether the property is subject to family disputes, government acquisition, or financial collateral commitments. Working with an experienced local advisory ensures every document is scrutinized through official registries before contracts are finalized. Category: Buying. Read time: 4 min read. Published: Advisory Note.', '{"category":"Buying","readTime":"4 min read","publishDate":"Advisory Note"}'::jsonb
),
(
  'insight-insight-2', 'insight', 'Maximizing Commercial Asset Value on Major Uyo Thoroughfares (Selling)', 'Maximizing Commercial Asset Value on Major Uyo Thoroughfares — Why frontage positioning on Aka Road and Abak Road dictates long-term commercial yields and how owners can optimize asset positioning. Commercial property on major arterial corridors in Uyo commands distinct valuation premiums based on access, frontage width, and utility infrastructure. 1. Clear Frontage & Accessibility: Arterials like Aka Road and Abak Road benefit from steady traffic flow. Properties with dedicated deceleration ingress and surface parking retain significant tenant demand. 2. Utility Independence: Commercial tenants in Uyo prioritize locations with dedicated transformer infrastructure and guaranteed borehole water access. 3. Professional Presentation: Well-documented floorplans and structural costing documentation dramatically accelerate transaction timelines with institutional buyers. Category: Selling. Read time: 5 min read. Published: Market Briefing.', '{"category":"Selling","readTime":"5 min read","publishDate":"Market Briefing"}'::jsonb
),
(
  'insight-insight-3', 'insight', 'Tenant Retention and Asset Preservation in Growing Urban Centers (Property Management)', 'Tenant Retention and Asset Preservation in Growing Urban Centers — How structured management practices safeguard capital appreciation while maintaining steady rental yields for diaspora and local landlords. Passive property ownership requires active, professional management on the ground. 1. Structured Tenant Onboarding: Comprehensive background evaluation and clear tenancy agreements establish expectations from day one. 2. Preventative Maintenance Cycles: Routine roof, plumbing, and electrical inspections prevent minor drainage and structural wear from compounding into major capital outlays. 3. Transparent Reporting: Clear monthly statements and direct rent disbursements give absentee owners complete peace of mind without operational friction. Category: Property Management. Read time: 4 min read. Published: Management Perspective.', '{"category":"Property Management","readTime":"4 min read","publishDate":"Management Perspective"}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  title = EXCLUDED.title,
  content = EXCLUDED.content,
  meta = EXCLUDED.meta,
  updated_at = now();
