// Generates the lh_ seed migration straight from src/data/mockData.ts so the
// database can never drift from what the frontend renders.
//
//   node scripts/gen-seed.mjs
//
// Bundles the TS module with the project's own esbuild, then emits:
//   * 24 rows into lh_property
//   * prose docs into lh_knowledge (business profile, locations, services, insights)

import { build } from 'esbuild';
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tmp = join(root, '.tmp-seed');
mkdirSync(tmp, { recursive: true });

const bundlePath = join(tmp, 'mockData.mjs');
await build({
  entryPoints: [join(root, 'src', 'data', 'mockData.ts')],
  outfile: bundlePath,
  bundle: true,
  format: 'esm',
  platform: 'node',
  logLevel: 'error',
});

const M = await import(pathToFileURL(bundlePath).href);

const q = (v) =>
  v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;
const qn = (v) => (v === null || v === undefined || v === '' ? 'NULL' : Number(v));
const qj = (v) => `'${JSON.stringify(v ?? null).replace(/'/g, "''")}'::jsonb`;
const firstInt = (s) => {
  if (!s) return null;
  const m = String(s).match(/[\d,]+/);
  return m ? parseInt(m[0].replace(/,/g, ''), 10) : null;
};

const STATUS = {
  'Available': 'available',
  'Under Offer': 'under_offer',
  'Exclusive Advisory': 'exclusive_advisory',
};

const propRows = M.PROPERTIES_DATA.map((p) => {
  const features = {
    galleryImages: p.galleryImages ?? [],
    featured: p.featured ?? false,
    location: p.location,
    typeLabel: p.type,
    purposeLabel: p.purpose,
  };
  return `(
  ${q(p.id)}, ${q(p.title)}, ${q(p.type)}, ${q(p.purpose)}, ${q(p.location)}, ${q(p.zone)},
  ${qn(p.priceRaw)}, ${q(p.currency)}, ${q(p.priceFormatted)},
  ${qn(p.beds)}, ${qn(p.baths)}, ${qn(firstInt(p.sizeSqFt))}, ${qn(firstInt(p.plotSize))},
  ${q(p.sizeSqFt ?? null)}, ${q(p.description)}, ${qj(p.highlights ?? [])}, ${qj(features)},
  ${q(p.imageUrl ?? null)}, ${q(STATUS[p.status] ?? 'available')},
  ${p.editorialHighlight ? 'true' : 'false'}, ${p.isIllustrative ? 'true' : 'false'}
)`;
}).join(',\n');

const docs = [];

const b = M.BUSINESS_INFO;
docs.push({
  slug: 'business-profile',
  category: 'business',
  title: `${b.name} — company profile and contact details`,
  meta: { phone: b.phoneClean, whatsapp: b.whatsappClean },
  content: [
    `${b.name} is a ${b.category} based at ${b.address}.`,
    `Phone: ${b.phone}. WhatsApp: ${b.phoneClean}.`,
    `Rating: ${b.googleRating} from ${b.googleReviewCount} Google reviews.`,
    `Operating hours: ${b.operatingHours}.`,
    `A client review reads: "${b.officialReview}"`,
  ].join(' '),
});

for (const l of M.LOCATIONS_DATA ?? []) {
  docs.push({
    slug: `location-${l.id}`,
    category: 'location',
    title: `${l.name} — ${l.tagline}`,
    meta: { propertyCount: l.propertyCount, character: l.character },
    content: [
      `${l.name}: ${l.tagline}.`,
      l.description,
      `${l.propertyCount} listings in this area.`,
      `Character: ${l.character}.`,
    ].join(' '),
  });
}

for (const s of M.SERVICES_DATA ?? []) {
  docs.push({
    slug: `service-${s.id}`,
    category: 'service',
    title: `${s.title} — ${s.subtitle}`,
    meta: { tag: s.tag },
    content: [
      `${s.title} (${s.subtitle}): ${s.description}`,
      `Key deliverables: ${(s.keyDeliverables ?? []).join('; ')}.`,
    ].join(' '),
  });
}

for (const i of M.INSIGHTS_DATA ?? []) {
  docs.push({
    slug: `insight-${i.id}`,
    category: 'insight',
    title: `${i.title} (${i.category})`,
    meta: { category: i.category, readTime: i.readTime, publishDate: i.publishDate },
    content: [
      `${i.title} — ${i.summary}`,
      (i.fullContent ?? []).join(' '),
      `Category: ${i.category}. Read time: ${i.readTime}. Published: ${i.publishDate}.`,
    ].join(' '),
  });
}

const docRows = docs.map((d) => `(
  ${q(d.slug)}, ${q(d.category)}, ${q(d.title)}, ${q(d.content)}, ${qj(d.meta)}
)`).join(',\n');

const stamp = process.env.SEED_STAMP || new Date().toISOString().replace(/[-:]/g, '').slice(0, 14);
const outFile = join(root, 'migrations', `${stamp}_lh-concierge-seed.sql`);

const sql = `-- LandsandHousing Property Concierge — seed
-- GENERATED by scripts/gen-seed.mjs from src/data/mockData.ts — do not hand-edit.
-- Regenerate with: node scripts/gen-seed.mjs
--
-- Upserts by natural key, so re-running refreshes catalogue copy without ever
-- touching lh_lead / lh_conversation / lh_booking rows.
--
-- ${M.PROPERTIES_DATA.length} properties, ${docs.length} knowledge documents.

INSERT INTO lh_property (
  id, title, property_type, purpose, location, zone, price_raw, currency,
  price_label, beds, baths, size_sqm, plot_sqm, title_document, description,
  highlights, features, image_url, status, editorial_highlight, is_illustrative
) VALUES
${propRows}
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  property_type = EXCLUDED.property_type,
  purpose = EXCLUDED.purpose,
  location = EXCLUDED.location,
  zone = EXCLUDED.zone,
  price_raw = EXCLUDED.price_raw,
  currency = EXCLUDED.currency,
  price_label = EXCLUDED.price_label,
  beds = EXCLUDED.beds,
  baths = EXCLUDED.baths,
  size_sqm = EXCLUDED.size_sqm,
  plot_sqm = EXCLUDED.plot_sqm,
  title_document = EXCLUDED.title_document,
  description = EXCLUDED.description,
  highlights = EXCLUDED.highlights,
  features = EXCLUDED.features,
  image_url = EXCLUDED.image_url,
  status = EXCLUDED.status,
  editorial_highlight = EXCLUDED.editorial_highlight,
  is_illustrative = EXCLUDED.is_illustrative,
  updated_at = now();

INSERT INTO lh_knowledge (slug, category, title, content, meta) VALUES
${docRows}
ON CONFLICT (slug) DO UPDATE SET
  category = EXCLUDED.category,
  title = EXCLUDED.title,
  content = EXCLUDED.content,
  meta = EXCLUDED.meta,
  updated_at = now();
`;

writeFileSync(outFile, sql, 'utf8');
rmSync(tmp, { recursive: true, force: true });

console.log(`Wrote ${outFile}`);
console.log(`  properties:  ${M.PROPERTIES_DATA.length}`);
console.log(`  knowledge:   ${docs.length}`);
const byCat = docs.reduce((a, d) => ((a[d.category] = (a[d.category] || 0) + 1), a), {});
console.log(`  by category: ${JSON.stringify(byCat)}`);